function mission = missionLibrary(missionNumber)
% MISSIONLIBRARY Pre-defined SAE Aero Design mission scenarios
%
% Returns complete mission configuration for specified mission number
% Includes Aerospace Blockset wind model parameters for Simulink
%
% SYNTAX:
%   mission = missionLibrary(missionNumber)
%
% INPUTS:
%   missionNumber - Integer 1-10 (see list below)
%
% OUTPUTS:
%   mission - Complete mission structure with all parameters
%
% AVAILABLE MISSIONS:
%   === CORE COMPETITION MISSIONS (Required) ===
%   1 - Baseline Flight           (1.0x) Easy
%   2 - Warm Day Operations       (1.5x) Moderate  
%   3 - Gusty Conditions          (2.0x) Moderate-Hard
%   4 - High Altitude Challenge   (2.5x) Hard
%   5 - Adverse Weather           (3.0x) Very Hard
%
%   === OPTIONAL CHALLENGE MISSIONS ===
%   6 - Precision Landing         (1.8x) Moderate
%   7 - Maximum Payload           (2.2x) Hard
%   8 - Speed Run                 (1.5x) Moderate
%   9 - Endurance Challenge       (2.0x) Moderate-Hard
%   10 - Emergency Procedures     (3.5x) Extreme
%
% EXAMPLE:
%   % Load Mission 1 (Baseline)
%   mission = missionLibrary(1);
%   
%   % Load Mission 5 (Adverse Weather)
%   mission = missionLibrary(5);
%
% Author: MathWorks Aerospace Team
% Date: 2026-01-13
% Updated: 2026-01-13 - Added Aerospace Blockset wind parameters

%% Validate Input
if nargin < 1
    error('Mission number required. Use: mission = missionLibrary(1) for Mission 1');
end

if ~isnumeric(missionNumber) || missionNumber < 1 || missionNumber > 10
    error('Mission number must be 1-10. See "help missionLibrary" for list');
end

%% Load Aircraft Parameters (must exist in workspace)
if ~evalin('base', 'exist(''mass'', ''var'')')
    error('Aircraft parameters not loaded. Run initialSetup1.m first');
end

mass = evalin('base', 'mass');

%% Mission Definitions
switch missionNumber
    case 1
        mission = mission1_Baseline(mass);
    case 2
        mission = mission2_WarmDay(mass);
    case 3
        mission = mission3_Gusty(mass);
    case 4
        mission = mission4_HighAltitude(mass);
    case 5
        mission = mission5_AdverseWeather(mass);
    case 6
        mission = mission6_PrecisionLanding(mass);
    case 7
        mission = mission7_MaxPayload(mass);
    case 8
        mission = mission8_SpeedRun(mass);
    case 9
        mission = mission9_Endurance(mass);
    case 10
        mission = mission10_Emergency(mass);
end

%% Display Mission Summary
displayMissionSummary(mission);

end

%% ========================================================================
%  CORE COMPETITION MISSIONS
%  ========================================================================

function mission = mission1_Baseline(mass)
% MISSION 1: Baseline Flight - Establish nominal performance

missionID = struct(...
    'Number', 1, ...
    'Name', 'Baseline Flight', ...
    'Date', date, ...
    'Description', 'Nominal operations at sea level with calm conditions', ...
    'ChallengeLevel', 'Easy', ...
    'Multiplier', 1.0, ...
    'KeyTestAreas', 'Baseline performance, nominal operations, payload handling' ...
);

% Payload
missionPayload = struct(...
    'weight_kg', 4.54, ...                % 10 lbs standard
    'description', 'Standard payload - soccer ball', ...
    'adjustTotalMass', true ...
);

% Update total mass
if missionPayload.adjustTotalMass
    mass.payload_kg = missionPayload.weight_kg;
    mass.total_kg = mass.empty_kg + mass.payload_kg + mass.battery_kg;
    assignin('base', 'mass', mass);
end

% Environment - Sea Level ISA Standard
[T_K, P_Pa, rho_kgm3] = atmosphereISA(0, 0);  % Sea level, ISA standard

% Lakeland FL Location
location = struct(...
    'Name', 'Lakeland Linder International Airport', ...
    'City', 'Lakeland', ...
    'State', 'FL', ...
    'Latitude_deg', 27.9889, ...
    'Longitude_deg', -81.9478, ...
    'Elevation_MSL_m', 43.3 ...           % 142 ft
);

% Wind Shear Model parameters (Aerospace Blockset)
windShear = struct(...
    'WindSpeed_6m_mps', 0.89, ...         % 2 mph variable wind
    'WindDirection_6m_deg', 0, ...        % Variable, use North
    'ReferenceAltitude_m', 6, ...         % Standard reference altitude
    'ShearExponent', 0.14 ...             % Grass field roughness
);

% Wind Turbulence Model parameters (Aerospace Blockset)
windTurbulence = struct(...
    'WindSpeed_6m_mps', 0.89, ...
    'WindDirection_6m_deg', 0, ...
    'TurbulenceIntensity', 'Light', ...
    'ProbabilityExceedance', 0.01, ...    % Very light turbulence
    'LengthScale_Lu_m', 50, ...           % Longitudinal scale
    'LengthScale_Lv_m', 50, ...           % Lateral scale
    'LengthScale_Lw_m', 25, ...           % Vertical scale
    'NoiseSeeds', [23341 23342 23343 23344] ... % Random seeds
);

% Discrete Wind Gust Model parameters (Aerospace Blockset)
windGust = struct(...
    'GustAmplitude_mps', [0 0 0], ...     % No gust [ug vg wg]
    'GustLength_m', [1 1 1], ...          % Minimum (not active)
    'GustStartTime_sec', 999, ...         % Never occurs
    'GustStartAltitude_m', 0 ...
);

environment = struct(...
    'Altitude_MSL_m', 0, ...              % Sea level
    'Temperature_C', 15, ...              % ISA standard (59°F)
    'DensityAltitude_m', 0, ...           % Same as pressure altitude
    'Pressure_Pa', P_Pa, ...
    'AirDensity_kgm3', rho_kgm3, ...
    'WindSpeed_mps', 0.89, ...            % 2 mph (calm) - for display
    'WindDirection_deg', 0, ...           % Variable - for display
    'WindGust_mps', 1.34, ...             % 3 mph - for display
    'Turbulence', 'none', ...             % For display
    'VisibilityDescription', 'Excellent', ...
    'Location', location, ...             % Lakeland FL
    'WindShear', windShear, ...           % Aerospace Blockset parameters
    'WindTurbulence', windTurbulence, ... % Aerospace Blockset parameters
    'WindGust', windGust ...              % Aerospace Blockset parameters
);

mission = createMissionStructure(missionID, missionPayload, environment, mass);
end

function mission = mission2_WarmDay(mass)
% MISSION 2: Warm Day Operations - Reduced performance

missionID = struct(...
    'Number', 2, ...
    'Name', 'Warm Day Operations', ...
    'Date', date, ...
    'Description', 'Hot day with crosswind - reduced lift and thrust', ...
    'ChallengeLevel', 'Moderate', ...
    'Multiplier', 1.5, ...
    'KeyTestAreas', 'Reduced lift/thrust, crosswind takeoff/landing, lateral control' ...
);

missionPayload = struct(...
    'weight_kg', 4.54, ...
    'description', 'Standard payload', ...
    'adjustTotalMass', true ...
);

if missionPayload.adjustTotalMass
    mass.payload_kg = missionPayload.weight_kg;
    mass.total_kg = mass.empty_kg + mass.payload_kg + mass.battery_kg;
    assignin('base', 'mass', mass);
end

% 4,000 ft density altitude (ISA +15°C)
pressureAlt_m = 1219.2;  % 4,000 ft
tempDev_C = 15;
[T_K, P_Pa, rho_kgm3] = atmosphereISA(pressureAlt_m, tempDev_C);

% Lakeland FL Location
location = struct(...
    'Name', 'Lakeland Linder International Airport', ...
    'City', 'Lakeland', ...
    'State', 'FL', ...
    'Latitude_deg', 27.9889, ...
    'Longitude_deg', -81.9478, ...
    'Elevation_MSL_m', 43.3 ...
);

% Wind Shear Model
windShear = struct(...
    'WindSpeed_6m_mps', 3.58, ...         % 8 mph
    'WindDirection_6m_deg', 90, ...       % Crosswind (East)
    'ReferenceAltitude_m', 6, ...
    'ShearExponent', 0.14 ...
);

% Wind Turbulence Model
windTurbulence = struct(...
    'WindSpeed_6m_mps', 3.58, ...
    'WindDirection_6m_deg', 90, ...
    'TurbulenceIntensity', 'Light', ...
    'ProbabilityExceedance', 0.05, ...
    'LengthScale_Lu_m', 75, ...
    'LengthScale_Lv_m', 75, ...
    'LengthScale_Lw_m', 35, ...
    'NoiseSeeds', [23341 23342 23343 23344] ...
);

% Discrete Wind Gust Model (none - steady wind)
windGust = struct(...
    'GustAmplitude_mps', [0 0 0], ...
    'GustLength_m', [1 1 1], ...
    'GustStartTime_sec', 999, ...
    'GustStartAltitude_m', 0 ...
);

environment = struct(...
    'Altitude_MSL_m', 1219.2, ...         % 4,000 ft
    'Temperature_C', T_K - 273.15, ...
    'DensityAltitude_m', calculateDensityAltitude(pressureAlt_m, tempDev_C), ...
    'Pressure_Pa', P_Pa, ...
    'AirDensity_kgm3', rho_kgm3, ...
    'WindSpeed_mps', 3.58, ...            % 8 mph steady - for display
    'WindDirection_deg', 90, ...          % Crosswind - for display
    'WindGust_mps', 0, ...                % Steady - for display
    'Turbulence', 'light', ...            % For display
    'VisibilityDescription', 'Good', ...
    'Location', location, ...
    'WindShear', windShear, ...
    'WindTurbulence', windTurbulence, ...
    'WindGust', windGust ...
);

mission = createMissionStructure(missionID, missionPayload, environment, mass);
end

function mission = mission3_Gusty(mass)
% MISSION 3: Gusty Conditions - Control challenge

missionID = struct(...
    'Number', 3, ...
    'Name', 'Gusty Conditions', ...
    'Date', date, ...
    'Description', 'Moderate gusts at angle to runway', ...
    'ChallengeLevel', 'Moderate-Hard', ...
    'Multiplier', 2.0, ...
    'KeyTestAreas', 'Gust response, control damping, approach stability' ...
);

missionPayload = struct(...
    'weight_kg', 4.54, ...
    'description', 'Standard payload', ...
    'adjustTotalMass', true ...
);

if missionPayload.adjustTotalMass
    mass.payload_kg = missionPayload.weight_kg;
    mass.total_kg = mass.empty_kg + mass.payload_kg + mass.battery_kg;
    assignin('base', 'mass', mass);
end

% 2,000 ft (ISA +5°C)
pressureAlt_m = 609.6;  % 2,000 ft
tempDev_C = 5;
[T_K, P_Pa, rho_kgm3] = atmosphereISA(pressureAlt_m, tempDev_C);

% Lakeland FL Location
location = struct(...
    'Name', 'Lakeland Linder International Airport', ...
    'City', 'Lakeland', ...
    'State', 'FL', ...
    'Latitude_deg', 27.9889, ...
    'Longitude_deg', -81.9478, ...
    'Elevation_MSL_m', 43.3 ...
);

% Wind Shear Model
windShear = struct(...
    'WindSpeed_6m_mps', 5.36, ...         % 12 mph base
    'WindDirection_6m_deg', 45, ...       % 45° to runway
    'ReferenceAltitude_m', 6, ...
    'ShearExponent', 0.14 ...
);

% Wind Turbulence Model
windTurbulence = struct(...
    'WindSpeed_6m_mps', 5.36, ...
    'WindDirection_6m_deg', 45, ...
    'TurbulenceIntensity', 'Moderate', ...
    'ProbabilityExceedance', 0.1, ...     % Moderate
    'LengthScale_Lu_m', 100, ...
    'LengthScale_Lv_m', 100, ...
    'LengthScale_Lw_m', 50, ...
    'NoiseSeeds', [23341 23342 23343 23344] ...
);

% Discrete Wind Gust Model (6 mph added = 18 mph peak)
gustMagnitude = 2.69;  % 6 mph = 2.69 m/s
windGust = struct(...
    'GustAmplitude_mps', [gustMagnitude*cosd(45) gustMagnitude*sind(45) 0], ...
    'GustLength_m', [150 150 75], ...     % Medium gust size
    'GustStartTime_sec', 45, ...          % During cruise
    'GustStartAltitude_m', 30 ...         % ~100 ft
);

environment = struct(...
    'Altitude_MSL_m', 609.6, ...          % 2,000 ft
    'Temperature_C', T_K - 273.15, ...
    'DensityAltitude_m', calculateDensityAltitude(pressureAlt_m, tempDev_C), ...
    'Pressure_Pa', P_Pa, ...
    'AirDensity_kgm3', rho_kgm3, ...
    'WindSpeed_mps', 5.36, ...            % 12 mph - for display
    'WindDirection_deg', 45, ...          % 45° to runway - for display
    'WindGust_mps', 8.05, ...             % Gusts to 18 mph - for display
    'Turbulence', 'moderate', ...         % For display
    'VisibilityDescription', 'Fair', ...
    'Location', location, ...
    'WindShear', windShear, ...
    'WindTurbulence', windTurbulence, ...
    'WindGust', windGust ...
);

mission = createMissionStructure(missionID, missionPayload, environment, mass);
end

function mission = mission4_HighAltitude(mass)
% MISSION 4: High Altitude Challenge - Power limitations

missionID = struct(...
    'Number', 4, ...
    'Name', 'High Altitude Challenge', ...
    'Date', date, ...
    'Description', 'Thin air operations with reduced power', ...
    'ChallengeLevel', 'Hard', ...
    'Multiplier', 2.5, ...
    'KeyTestAreas', 'Power limitations, thin air handling, extended takeoff/landing' ...
);

missionPayload = struct(...
    'weight_kg', 4.54, ...
    'description', 'Standard payload', ...
    'adjustTotalMass', true ...
);

if missionPayload.adjustTotalMass
    mass.payload_kg = missionPayload.weight_kg;
    mass.total_kg = mass.empty_kg + mass.payload_kg + mass.battery_kg;
    assignin('base', 'mass', mass);
end

% 8,000 ft (ISA +10°C)
pressureAlt_m = 2438.4;  % 8,000 ft
tempDev_C = 10;
[T_K, P_Pa, rho_kgm3] = atmosphereISA(pressureAlt_m, tempDev_C);

% Lakeland FL Location
location = struct(...
    'Name', 'Lakeland Linder International Airport', ...
    'City', 'Lakeland', ...
    'State', 'FL', ...
    'Latitude_deg', 27.9889, ...
    'Longitude_deg', -81.9478, ...
    'Elevation_MSL_m', 43.3 ...
);

% Wind Shear Model
windShear = struct(...
    'WindSpeed_6m_mps', 4.47, ...         % 10 mph
    'WindDirection_6m_deg', 0, ...        % Headwind (North)
    'ReferenceAltitude_m', 6, ...
    'ShearExponent', 0.10 ...             % Less shear at altitude
);

% Wind Turbulence Model
windTurbulence = struct(...
    'WindSpeed_6m_mps', 4.47, ...
    'WindDirection_6m_deg', 0, ...
    'TurbulenceIntensity', 'Light', ...
    'ProbabilityExceedance', 0.05, ...
    'LengthScale_Lu_m', 150, ...          % Larger scales at altitude
    'LengthScale_Lv_m', 150, ...
    'LengthScale_Lw_m', 75, ...
    'NoiseSeeds', [23341 23342 23343 23344] ...
);

% Discrete Wind Gust Model (none)
windGust = struct(...
    'GustAmplitude_mps', [0 0 0], ...
    'GustLength_m', [1 1 1], ...
    'GustStartTime_sec', 999, ...
    'GustStartAltitude_m', 0 ...
);

environment = struct(...
    'Altitude_MSL_m', 2438.4, ...         % 8,000 ft
    'Temperature_C', T_K - 273.15, ...
    'DensityAltitude_m', calculateDensityAltitude(pressureAlt_m, tempDev_C), ...
    'Pressure_Pa', P_Pa, ...
    'AirDensity_kgm3', rho_kgm3, ...
    'WindSpeed_mps', 4.47, ...            % 10 mph headwind - for display
    'WindDirection_deg', 0, ...           % Headwind - for display
    'WindGust_mps', 0, ...                % For display
    'Turbulence', 'light', ...            % For display
    'VisibilityDescription', 'Good', ...
    'Location', location, ...
    'WindShear', windShear, ...
    'WindTurbulence', windTurbulence, ...
    'WindGust', windGust ...
);

mission = createMissionStructure(missionID, missionPayload, environment, mass);
end

function mission = mission5_AdverseWeather(mass)
% MISSION 5: Adverse Weather - Maximum challenge

missionID = struct(...
    'Number', 5, ...
    'Name', 'Adverse Weather', ...
    'Date', date, ...
    'Description', 'Strong crosswind gusts with wind shear', ...
    'ChallengeLevel', 'Very Hard', ...
    'Multiplier', 3.0, ...
    'KeyTestAreas', 'Maximum control authority, decision-making, go-around capability' ...
);

missionPayload = struct(...
    'weight_kg', 4.54, ...
    'description', 'Standard payload', ...
    'adjustTotalMass', true ...
);

if missionPayload.adjustTotalMass
    mass.payload_kg = missionPayload.weight_kg;
    mass.total_kg = mass.empty_kg + mass.payload_kg + mass.battery_kg;
    assignin('base', 'mass', mass);
end

% 3,000 ft (ISA +10°C)
pressureAlt_m = 914.4;  % 3,000 ft
tempDev_C = 10;
[T_K, P_Pa, rho_kgm3] = atmosphereISA(pressureAlt_m, tempDev_C);

% Lakeland FL Location
location = struct(...
    'Name', 'Lakeland Linder International Airport', ...
    'City', 'Lakeland', ...
    'State', 'FL', ...
    'Latitude_deg', 27.9889, ...
    'Longitude_deg', -81.9478, ...
    'Elevation_MSL_m', 43.3 ...
);

% Wind Shear Model (includes wind shear layer at 100 ft)
windShear = struct(...
    'WindSpeed_6m_mps', 6.71, ...         % 15 mph base
    'WindDirection_6m_deg', 90, ...       % Crosswind
    'ReferenceAltitude_m', 6, ...
    'ShearExponent', 0.20 ...             % Strong shear
);

% Wind Turbulence Model
windTurbulence = struct(...
    'WindSpeed_6m_mps', 6.71, ...
    'WindDirection_6m_deg', 90, ...
    'TurbulenceIntensity', 'Moderate', ...
    'ProbabilityExceedance', 0.15, ...    % Strong moderate
    'LengthScale_Lu_m', 120, ...
    'LengthScale_Lv_m', 120, ...
    'LengthScale_Lw_m', 60, ...
    'NoiseSeeds', [23341 23342 23343 23344] ...
);

% Discrete Wind Gust Model (7 mph added = 22 mph peak)
gustMagnitude = 3.13;  % 7 mph = 3.13 m/s
windGust = struct(...
    'GustAmplitude_mps', [0 gustMagnitude 0], ... % Crosswind gust
    'GustLength_m', [200 200 100], ...    % Large gust
    'GustStartTime_sec', 90, ...          % During approach
    'GustStartAltitude_m', 30.48 ...      % 100 ft AGL (shear layer)
);

environment = struct(...
    'Altitude_MSL_m', 914.4, ...          % 3,000 ft
    'Temperature_C', T_K - 273.15, ...
    'DensityAltitude_m', calculateDensityAltitude(pressureAlt_m, tempDev_C), ...
    'Pressure_Pa', P_Pa, ...
    'AirDensity_kgm3', rho_kgm3, ...
    'WindSpeed_mps', 6.71, ...            % 15 mph - for display
    'WindDirection_deg', 90, ...          % Crosswind - for display
    'WindGust_mps', 9.83, ...             % Gusts to 22 mph - for display
    'WindShear_present', true, ...        % For display
    'WindShear_altitude_m', 30.48, ...    % 100 ft AGL - for display
    'WindShear_strength_mps', 4.47, ...   % 10 mph change - for display
    'Turbulence', 'moderate', ...         % For display
    'VisibilityDescription', 'Marginal', ...
    'Location', location, ...
    'WindShear', windShear, ...
    'WindTurbulence', windTurbulence, ...
    'WindGust', windGust ...
);

mission = createMissionStructure(missionID, missionPayload, environment, mass);
end

%% ========================================================================
%  OPTIONAL CHALLENGE MISSIONS
%  ========================================================================

function mission = mission6_PrecisionLanding(mass)
% MISSION 6: Precision Landing Challenge

missionID = struct(...
    'Number', 6, ...
    'Name', 'Precision Landing Challenge', ...
    'Date', date, ...
    'Description', 'Land within 10m target zone with crosswind', ...
    'ChallengeLevel', 'Moderate', ...
    'Multiplier', 1.8, ...
    'KeyTestAreas', 'Approach control, touchdown accuracy, energy management' ...
);

missionPayload = struct(...
    'weight_kg', 2.27, ...                % Light payload for precision
    'description', 'Light payload for precision control', ...
    'adjustTotalMass', true ...
);

if missionPayload.adjustTotalMass
    mass.payload_kg = missionPayload.weight_kg;
    mass.total_kg = mass.empty_kg + mass.payload_kg + mass.battery_kg;
    assignin('base', 'mass', mass);
end

pressureAlt_m = 0;
tempDev_C = 5;
[T_K, P_Pa, rho_kgm3] = atmosphereISA(pressureAlt_m, tempDev_C);

% Lakeland FL Location
location = struct(...
    'Name', 'Lakeland Linder International Airport', ...
    'City', 'Lakeland', ...
    'State', 'FL', ...
    'Latitude_deg', 27.9889, ...
    'Longitude_deg', -81.9478, ...
    'Elevation_MSL_m', 43.3 ...
);

% Wind Shear Model
windShear = struct(...
    'WindSpeed_6m_mps', 4.47, ...         % 10 mph crosswind
    'WindDirection_6m_deg', 60, ...
    'ReferenceAltitude_m', 6, ...
    'ShearExponent', 0.14 ...
);

% Wind Turbulence Model
windTurbulence = struct(...
    'WindSpeed_6m_mps', 4.47, ...
    'WindDirection_6m_deg', 60, ...
    'TurbulenceIntensity', 'Light', ...
    'ProbabilityExceedance', 0.05, ...
    'LengthScale_Lu_m', 60, ...
    'LengthScale_Lv_m', 60, ...
    'LengthScale_Lw_m', 30, ...
    'NoiseSeeds', [23341 23342 23343 23344] ...
);

% Discrete Wind Gust Model (none)
windGust = struct(...
    'GustAmplitude_mps', [0 0 0], ...
    'GustLength_m', [1 1 1], ...
    'GustStartTime_sec', 999, ...
    'GustStartAltitude_m', 0 ...
);

environment = struct(...
    'Altitude_MSL_m', 0, ...
    'Temperature_C', T_K - 273.15, ...
    'DensityAltitude_m', calculateDensityAltitude(pressureAlt_m, tempDev_C), ...
    'Pressure_Pa', P_Pa, ...
    'AirDensity_kgm3', rho_kgm3, ...
    'WindSpeed_mps', 4.47, ...            % 10 mph crosswind - for display
    'WindDirection_deg', 60, ...          % For display
    'WindGust_mps', 0, ...                % For display
    'Turbulence', 'light', ...            % For display
    'VisibilityDescription', 'Good', ...
    'PrecisionTarget_m', 10, ...          % 10m target zone
    'Location', location, ...
    'WindShear', windShear, ...
    'WindTurbulence', windTurbulence, ...
    'WindGust', windGust ...
);

mission = createMissionStructure(missionID, missionPayload, environment, mass);
mission.Requirements.PrecisionLanding = true;
mission.Requirements.TargetZone_m = 10;
end

function mission = mission7_MaxPayload(mass)
% MISSION 7: Maximum Payload Challenge

missionID = struct(...
    'Number', 7, ...
    'Name', 'Maximum Payload Challenge', ...
    'Date', date, ...
    'Description', 'Maximum possible payload within weight limit', ...
    'ChallengeLevel', 'Hard', ...
    'Multiplier', 2.2, ...
    'KeyTestAreas', 'Thrust margin, climb performance, handling at high weight' ...
);

% Calculate maximum possible payload
maxTotalWeight_kg = 24.95;  % SAE limit
maxPayload_kg = min(9.07, maxTotalWeight_kg - mass.empty_kg - mass.battery_kg);

missionPayload = struct(...
    'weight_kg', maxPayload_kg, ...
    'description', sprintf('Maximum payload: %.2f kg', maxPayload_kg), ...
    'adjustTotalMass', true ...
);

if missionPayload.adjustTotalMass
    mass.payload_kg = missionPayload.weight_kg;
    mass.total_kg = mass.empty_kg + mass.payload_kg + mass.battery_kg;
    assignin('base', 'mass', mass);
end

pressureAlt_m = 609.6;  % 2,000 ft
tempDev_C = 10;
[T_K, P_Pa, rho_kgm3] = atmosphereISA(pressureAlt_m, tempDev_C);

% Lakeland FL Location
location = struct(...
    'Name', 'Lakeland Linder International Airport', ...
    'City', 'Lakeland', ...
    'State', 'FL', ...
    'Latitude_deg', 27.9889, ...
    'Longitude_deg', -81.9478, ...
    'Elevation_MSL_m', 43.3 ...
);

% Wind Shear Model
windShear = struct(...
    'WindSpeed_6m_mps', 2.68, ...         % 6 mph
    'WindDirection_6m_deg', 0, ...
    'ReferenceAltitude_m', 6, ...
    'ShearExponent', 0.14 ...
);

% Wind Turbulence Model
windTurbulence = struct(...
    'WindSpeed_6m_mps', 2.68, ...
    'WindDirection_6m_deg', 0, ...
    'TurbulenceIntensity', 'Light', ...
    'ProbabilityExceedance', 0.05, ...
    'LengthScale_Lu_m', 75, ...
    'LengthScale_Lv_m', 75, ...
    'LengthScale_Lw_m', 35, ...
    'NoiseSeeds', [23341 23342 23343 23344] ...
);

% Discrete Wind Gust Model (none)
windGust = struct(...
    'GustAmplitude_mps', [0 0 0], ...
    'GustLength_m', [1 1 1], ...
    'GustStartTime_sec', 999, ...
    'GustStartAltitude_m', 0 ...
);

environment = struct(...
    'Altitude_MSL_m', 609.6, ...
    'Temperature_C', T_K - 273.15, ...
    'DensityAltitude_m', calculateDensityAltitude(pressureAlt_m, tempDev_C), ...
    'Pressure_Pa', P_Pa, ...
    'AirDensity_kgm3', rho_kgm3, ...
    'WindSpeed_mps', 2.68, ...            % 6 mph - for display
    'WindDirection_deg', 0, ...           % For display
    'WindGust_mps', 0, ...                % For display
    'Turbulence', 'light', ...            % For display
    'VisibilityDescription', 'Good', ...
    'Location', location, ...
    'WindShear', windShear, ...
    'WindTurbulence', windTurbulence, ...
    'WindGust', windGust ...
);

mission = createMissionStructure(missionID, missionPayload, environment, mass);
end

function mission = mission8_SpeedRun(mass)
% MISSION 8: Speed Run Challenge

missionID = struct(...
    'Number', 8, ...
    'Name', 'Speed Run Challenge', ...
    'Date', date, ...
    'Description', 'Minimum time for 3 laps - light payload', ...
    'ChallengeLevel', 'Moderate', ...
    'Multiplier', 1.5, ...
    'KeyTestAreas', 'High-speed handling, turn performance, energy management' ...
);

missionPayload = struct(...
    'weight_kg', 1.36, ...                % 3 lbs - minimum payload
    'description', 'Minimum payload for speed', ...
    'adjustTotalMass', true ...
);

if missionPayload.adjustTotalMass
    mass.payload_kg = missionPayload.weight_kg;
    mass.total_kg = mass.empty_kg + mass.payload_kg + mass.battery_kg;
    assignin('base', 'mass', mass);
end

pressureAlt_m = 0;
tempDev_C = 0;
[T_K, P_Pa, rho_kgm3] = atmosphereISA(pressureAlt_m, tempDev_C);

% Lakeland FL Location
location = struct(...
    'Name', 'Lakeland Linder International Airport', ...
    'City', 'Lakeland', ...
    'State', 'FL', ...
    'Latitude_deg', 27.9889, ...
    'Longitude_deg', -81.9478, ...
    'Elevation_MSL_m', 43.3 ...
);

% Wind Shear Model (calm)
windShear = struct(...
    'WindSpeed_6m_mps', 0, ...            % Calm for fair comparison
    'WindDirection_6m_deg', 0, ...
    'ReferenceAltitude_m', 6, ...
    'ShearExponent', 0.14 ...
);

% Wind Turbulence Model (none)
windTurbulence = struct(...
    'WindSpeed_6m_mps', 0, ...
    'WindDirection_6m_deg', 0, ...
    'TurbulenceIntensity', 'Light', ...
    'ProbabilityExceedance', 0.01, ...
    'LengthScale_Lu_m', 50, ...
    'LengthScale_Lv_m', 50, ...
    'LengthScale_Lw_m', 25, ...
    'NoiseSeeds', [23341 23342 23343 23344] ...
);

% Discrete Wind Gust Model (none)
windGust = struct(...
    'GustAmplitude_mps', [0 0 0], ...
    'GustLength_m', [1 1 1], ...
    'GustStartTime_sec', 999, ...
    'GustStartAltitude_m', 0 ...
);

environment = struct(...
    'Altitude_MSL_m', 0, ...
    'Temperature_C', T_K - 273.15, ...
    'DensityAltitude_m', 0, ...
    'Pressure_Pa', P_Pa, ...
    'AirDensity_kgm3', rho_kgm3, ...
    'WindSpeed_mps', 0, ...               % Calm - for display
    'WindDirection_deg', 0, ...           % For display
    'WindGust_mps', 0, ...                % For display
    'Turbulence', 'none', ...             % For display
    'VisibilityDescription', 'Excellent', ...
    'Location', location, ...
    'WindShear', windShear, ...
    'WindTurbulence', windTurbulence, ...
    'WindGust', windGust ...
);

mission = createMissionStructure(missionID, missionPayload, environment, mass);
mission.Requirements.TargetLaps = 3;
mission.Requirements.TimeBonus = true;  % Bonus for fast completion
end

function mission = mission9_Endurance(mass)
% MISSION 9: Endurance Challenge

missionID = struct(...
    'Number', 9, ...
    'Name', 'Endurance Challenge', ...
    'Date', date, ...
    'Description', 'Maximum laps in time limit - light payload', ...
    'ChallengeLevel', 'Moderate-Hard', ...
    'Multiplier', 2.0, ...
    'KeyTestAreas', 'Energy efficiency, cruise optimization, battery management' ...
);

missionPayload = struct(...
    'weight_kg', 2.27, ...                % Light for efficiency
    'description', 'Light payload for endurance', ...
    'adjustTotalMass', true ...
);

if missionPayload.adjustTotalMass
    mass.payload_kg = missionPayload.weight_kg;
    mass.total_kg = mass.empty_kg + mass.payload_kg + mass.battery_kg;
    assignin('base', 'mass', mass);
end

pressureAlt_m = 0;
tempDev_C = 0;
[T_K, P_Pa, rho_kgm3] = atmosphereISA(pressureAlt_m, tempDev_C);

% Lakeland FL Location
location = struct(...
    'Name', 'Lakeland Linder International Airport', ...
    'City', 'Lakeland', ...
    'State', 'FL', ...
    'Latitude_deg', 27.9889, ...
    'Longitude_deg', -81.9478, ...
    'Elevation_MSL_m', 43.3 ...
);

% Wind Shear Model (calm)
windShear = struct(...
    'WindSpeed_6m_mps', 0, ...
    'WindDirection_6m_deg', 0, ...
    'ReferenceAltitude_m', 6, ...
    'ShearExponent', 0.14 ...
);

% Wind Turbulence Model (none)
windTurbulence = struct(...
    'WindSpeed_6m_mps', 0, ...
    'WindDirection_6m_deg', 0, ...
    'TurbulenceIntensity', 'Light', ...
    'ProbabilityExceedance', 0.01, ...
    'LengthScale_Lu_m', 50, ...
    'LengthScale_Lv_m', 50, ...
    'LengthScale_Lw_m', 25, ...
    'NoiseSeeds', [23341 23342 23343 23344] ...
);

% Discrete Wind Gust Model (none)
windGust = struct(...
    'GustAmplitude_mps', [0 0 0], ...
    'GustLength_m', [1 1 1], ...
    'GustStartTime_sec', 999, ...
    'GustStartAltitude_m', 0 ...
);

environment = struct(...
    'Altitude_MSL_m', 0, ...
    'Temperature_C', T_K - 273.15, ...
    'DensityAltitude_m', 0, ...
    'Pressure_Pa', P_Pa, ...
    'AirDensity_kgm3', rho_kgm3, ...
    'WindSpeed_mps', 0, ...               % For display
    'WindDirection_deg', 0, ...           % For display
    'WindGust_mps', 0, ...                % For display
    'Turbulence', 'none', ...             % For display
    'VisibilityDescription', 'Excellent', ...
    'Location', location, ...
    'WindShear', windShear, ...
    'WindTurbulence', windTurbulence, ...
    'WindGust', windGust ...
);

mission = createMissionStructure(missionID, missionPayload, environment, mass);
mission.Requirements.FlightTimeLimit_sec = 600;  % 10 minutes
mission.Requirements.TargetLaps = 999;  % As many as possible
end

function mission = mission10_Emergency(mass)
% MISSION 10: Emergency Procedures (Most Challenging)

missionID = struct(...
    'Number', 10, ...
    'Name', 'Emergency Procedures', ...
    'Date', date, ...
    'Description', 'Simulated motor failure at 50% throttle reduction', ...
    'ChallengeLevel', 'Extreme', ...
    'Multiplier', 3.5, ...
    'KeyTestAreas', 'Emergency handling, decision-making, safe landing with reduced power' ...
);

missionPayload = struct(...
    'weight_kg', 4.54, ...
    'description', 'Standard payload', ...
    'adjustTotalMass', true ...
);

if missionPayload.adjustTotalMass
    mass.payload_kg = missionPayload.weight_kg;
    mass.total_kg = mass.empty_kg + mass.payload_kg + mass.battery_kg;
    assignin('base', 'mass', mass);
end

pressureAlt_m = 609.6;  % 2,000 ft
tempDev_C = 5;
[T_K, P_Pa, rho_kgm3] = atmosphereISA(pressureAlt_m, tempDev_C);

% Lakeland FL Location
location = struct(...
    'Name', 'Lakeland Linder International Airport', ...
    'City', 'Lakeland', ...
    'State', 'FL', ...
    'Latitude_deg', 27.9889, ...
    'Longitude_deg', -81.9478, ...
    'Elevation_MSL_m', 43.3 ...
);

% Wind Shear Model
windShear = struct(...
    'WindSpeed_6m_mps', 4.47, ...         % 10 mph
    'WindDirection_6m_deg', 45, ...
    'ReferenceAltitude_m', 6, ...
    'ShearExponent', 0.14 ...
);

% Wind Turbulence Model
windTurbulence = struct(...
    'WindSpeed_6m_mps', 4.47, ...
    'WindDirection_6m_deg', 45, ...
    'TurbulenceIntensity', 'Moderate', ...
    'ProbabilityExceedance', 0.1, ...
    'LengthScale_Lu_m', 100, ...
    'LengthScale_Lv_m', 100, ...
    'LengthScale_Lw_m', 50, ...
    'NoiseSeeds', [23341 23342 23343 23344] ...
);

% Discrete Wind Gust Model
windGust = struct(...
    'GustAmplitude_mps', [3.0*cosd(45) 3.0*sind(45) 0], ... % 15 mph gusts
    'GustLength_m', [150 150 75], ...
    'GustStartTime_sec', 75, ...
    'GustStartAltitude_m', 50 ...
);

environment = struct(...
    'Altitude_MSL_m', 609.6, ...
    'Temperature_C', T_K - 273.15, ...
    'DensityAltitude_m', calculateDensityAltitude(pressureAlt_m, tempDev_C), ...
    'Pressure_Pa', P_Pa, ...
    'AirDensity_kgm3', rho_kgm3, ...
    'WindSpeed_mps', 4.47, ...            % 10 mph - for display
    'WindDirection_deg', 45, ...          % For display
    'WindGust_mps', 6.71, ...             % 15 mph gusts - for display
    'Turbulence', 'moderate', ...         % For display
    'VisibilityDescription', 'Fair', ...
    'MotorFailure', true, ...             % For display
    'MotorFailurePercent', 50, ...        % 50% power reduction - for display
    'Location', location, ...
    'WindShear', windShear, ...
    'WindTurbulence', windTurbulence, ...
    'WindGust', windGust ...
);

mission = createMissionStructure(missionID, missionPayload, environment, mass);
mission.Requirements.EmergencyProcedures = true;
end

%% ========================================================================
%  HELPER FUNCTIONS
%  ========================================================================

function mission = createMissionStructure(missionID, missionPayload, environment, mass)
% Create standard mission structure

% Standard course geometry (same for all missions)
course = struct(...
    'Type', 'Rectangular', ...
    'Length_m', 304.8, ...                % 1000 ft
    'Width_m', 121.92, ...                % 400 ft
    'TurnRadius_m', 45.72, ...            % 150 ft
    'Waypoints_m', [
        0     0;
        304.8 0;
        304.8 121.92;
        0     121.92;
        0     0
    ] ...
);

% Standard mission requirements
requirements = struct(...
    'MinLaps', 3, ...
    'TargetLaps', 3, ...
    'FlightTimeLimit_sec', 300, ...       % Changed to 300 seconds (5 minutes)
    'TakeoffTimeLimit_sec', 60, ...
    'RequireFullStop', false ...
);

% Altitude constraints
altitude = struct(...
    'Minimum_m', 3.05, ...                % 10 ft
    'Maximum_m', 121.92, ...              % 400 ft
    'Cruise_target_m', 30.48, ...         % 100 ft
    'Takeoff_clearance_m', 1.52 ...       % 5 ft
);

% Runway configuration
runway = struct(...
    'Length_m', 60.96, ...                % 200 ft
    'Width_m', 15.24, ...                 % 50 ft
    'Start_m', [0; 0], ...
    'Heading_deg', 0, ...
    'Surface', 'Grass' ...
);

% SAE limits (reference)
sae_limits = struct(...
    'MaxWingspan_m', 3.048, ...
    'MaxWeight_kg', 24.95, ...
    'MaxTakeoffDistance_m', 30.48, ...
    'MaxLandingDistance_m', 121.92, ...
    'MaxBatteryVoltage_V', 25.2, ...
    'MaxFlightTime_sec', 300 ...          % Changed to 300 seconds
);

% GPS fence
bufferZone_m = 15.24;
m_per_deg_lat = 111000;
m_per_deg_lon = 85000;

gpsFence = struct(...
    'MinLatitude', -(course.Length_m + bufferZone_m) / m_per_deg_lat / 2, ...
    'MaxLatitude',  (course.Length_m + bufferZone_m) / m_per_deg_lat / 2, ...
    'MinLongitude', -(course.Width_m + bufferZone_m) / m_per_deg_lon / 2, ...
    'MaxLongitude',  (course.Width_m + bufferZone_m) / m_per_deg_lon / 2, ...
    'BufferZone_m', bufferZone_m ...
);

% Scoring configuration
scoring = struct(...
    'MissionMultiplier', missionID.Multiplier, ...
    'BaseFormula', 'Score = (Payload / Empty Mass) × Laps × Multiplier', ...
    'PayloadWeight_kg', missionPayload.weight_kg, ...
    'EmptyWeight_kg', mass.empty_kg, ...
    'ExpectedBaseScore', (missionPayload.weight_kg / mass.empty_kg) * requirements.TargetLaps, ...
    'ExpectedTotalScore', (missionPayload.weight_kg / mass.empty_kg) * requirements.TargetLaps * missionID.Multiplier, ...
    'CompletionBonus', 1.0 ...            % Full bonus if completed
);

% Flight strategy
strategy = struct(...
    'CruiseSpeed_mps', 20, ...
    'ClimbRate_mps', 2.5, ...
    'TurnStrategy', 'Coordinated', ...
    'MaxBankAngle_deg', 35, ...
    'ThrottleStrategy', 'Constant', ...
    'LandingApproach', 'Standard' ...
);

% Combine into mission structure
mission = struct(...
    'ID', missionID, ...
    'Payload', missionPayload, ...
    'Course', course, ...
    'Requirements', requirements, ...
    'Altitude', altitude, ...
    'Environment', environment, ...
    'Runway', runway, ...
    'SAE_Limits', sae_limits, ...
    'GPSFence', gpsFence, ...
    'Scoring', scoring, ...
    'Strategy', strategy ...
);
end

function [T_K, P_Pa, rho_kgm3] = atmosphereISA(altitude_m, tempDev_C)
% ISA standard atmosphere with temperature deviation
% Based on International Standard Atmosphere (ISA)

% ISA constants
T0 = 288.15;              % Sea level temperature [K] (15°C)
P0 = 101325;              % Sea level pressure [Pa]
g = 9.80665;              % Gravity [m/s²]
R = 287.05;               % Gas constant [J/(kg·K)]
L = -0.0065;              % Lapse rate [K/m] in troposphere

% Standard temperature at altitude
T_std_K = T0 + L * altitude_m;

% Add temperature deviation
T_K = T_std_K + tempDev_C;

% Pressure (using standard lapse rate)
if altitude_m < 11000  % Troposphere
    P_Pa = P0 * (T_std_K / T0)^(-g / (L * R));
else  % Stratosphere (simplified)
    P_11000 = P0 * (216.65 / T0)^(-g / (L * R));
    P_Pa = P_11000 * exp(-g * (altitude_m - 11000) / (R * 216.65));
end

% Density
rho_kgm3 = P_Pa / (R * T_K);
end

function densityAlt_m = calculateDensityAltitude(pressureAlt_m, tempDev_C)
% Calculate density altitude from pressure altitude and temperature deviation
% Density altitude = pressure altitude + 120 ft per °C above standard

densityAlt_ft = pressureAlt_m / 0.3048;  % Convert to feet
densityAlt_ft = densityAlt_ft + (120 * tempDev_C);  % Add temperature effect
densityAlt_m = densityAlt_ft * 0.3048;  % Convert back to meters
end

function displayMissionSummary(mission)
% Display mission summary

fprintf('\n╔═══════════════════════════════════════════════════════════╗\n');
fprintf('║         MISSION %d: %-42s║\n', mission.ID.Number, mission.ID.Name);
fprintf('╚═══════════════════════════════════════════════════════════╝\n\n');

fprintf('Challenge Level: %s\n', mission.ID.ChallengeLevel);
fprintf('Score Multiplier: %.1fx\n', mission.ID.Multiplier);
fprintf('Key Test Areas: %s\n\n', mission.ID.KeyTestAreas);

fprintf('--- Location ---\n');
fprintf('%s\n', mission.Environment.Location.Name);
fprintf('Coordinates: %.4f°N, %.4f°W\n', ...
        mission.Environment.Location.Latitude_deg, ...
        abs(mission.Environment.Location.Longitude_deg));
fprintf('Elevation: %.1f m (%.0f ft MSL)\n\n', ...
        mission.Environment.Location.Elevation_MSL_m, ...
        mission.Environment.Location.Elevation_MSL_m/0.3048);

fprintf('--- Environmental Conditions ---\n');
fprintf('Altitude: %.0f m (%.0f ft MSL)\n', ...
        mission.Environment.Altitude_MSL_m, mission.Environment.Altitude_MSL_m/0.3048);
fprintf('Density Altitude: %.0f m (%.0f ft)\n', ...
        mission.Environment.DensityAltitude_m, mission.Environment.DensityAltitude_m/0.3048);
fprintf('Temperature: %.1f°C (%.1f°F)\n', ...
        mission.Environment.Temperature_C, mission.Environment.Temperature_C*9/5 + 32);
fprintf('Air Density: %.3f kg/m³ (%.1f%% of sea level)\n', ...
        mission.Environment.AirDensity_kgm3, mission.Environment.AirDensity_kgm3/1.225*100);

fprintf('\n--- Wind Conditions (Aerospace Blockset) ---\n');
fprintf('Wind Speed at 6m: %.2f m/s from %d° (%.1f mph)\n', ...
        mission.Environment.WindShear.WindSpeed_6m_mps, ...
        mission.Environment.WindShear.WindDirection_6m_deg, ...
        mission.Environment.WindShear.WindSpeed_6m_mps*2.237);
fprintf('Turbulence: %s (PE: %.2f)\n', ...
        mission.Environment.WindTurbulence.TurbulenceIntensity, ...
        mission.Environment.WindTurbulence.ProbabilityExceedance);
gustMag = norm(mission.Environment.WindGust.GustAmplitude_mps);
if gustMag > 0.1
    fprintf('Gust: %.2f m/s at t=%.0f sec (%.1f mph)\n', ...
            gustMag, mission.Environment.WindGust.GustStartTime_sec, gustMag*2.237);
else
    fprintf('Gust: None\n');
end

fprintf('\n--- Payload & Scoring ---\n');
fprintf('Payload: %.2f kg (%.2f lbs)\n', ...
        mission.Payload.weight_kg, mission.Payload.weight_kg/0.453592);
fprintf('Expected Score: %.2f × %.1fx = %.2f points\n', ...
        mission.Scoring.ExpectedBaseScore, mission.Scoring.MissionMultiplier, ...
        mission.Scoring.ExpectedTotalScore);

fprintf('\n');
end
