function [results, sensitivityResults] = runCustomEnvironmentParityTests
%RUNCUSTOMENVIRONMENTPARITYTESTS Verify custom environments in flight.

    modelName = 'SimulationDemo';
    wasLoaded = bdIsLoaded(modelName);
    if ~wasLoaded
        open_system(modelName);
    end

    environmentBlocks = find_system(modelName, ...
        'SearchDepth', 1, ...
        'MatchFilter', @Simulink.match.allVariants, ...
        'BlockType', 'SubSystem', ...
        'MaskType', 'SAE Aero Environment');
    assert(isscalar(environmentBlocks), ...
        'Expected one top-level SAE Aero Environment subsystem.');

    blockPath = environmentBlocks{1};
    mask = Simulink.Mask.get(blockPath);
    options = EnvironmentMask.presetOptions;
    assert(strcmp(options{1}, EnvironmentMask.customOption), ...
        'Custom environment must be the first mask option.');
    assert(numel(options) == 9, ...
        'Expected one custom option and eight preset options.');
    parameters = mask.Parameters;
    originalNames = {parameters.Name};
    originalValues = {parameters.Value};
    originalDirty = get_param(modelName, 'Dirty');
    modelWorkspace = get_param(modelName, 'ModelWorkspace');
    originalModelInitial = modelWorkspace.getVariable('initial');
    originalBaseInitial = evalin('base', 'initial');
    cleanup = onCleanup(@() restoreModel( ...
        modelName, blockPath, originalNames, originalValues, ...
        originalModelInitial, originalBaseInitial, ...
        originalDirty, wasLoaded));

    catalog = slResolve('envCatalog', blockPath);
    if isa(catalog, 'Simulink.Parameter')
        catalog = catalog.Value;
    end

    flight = struct( ...
        'AltitudeAGL_m', 200, ...
        'ForwardSpeed_mps', 18, ...
        'Pitch_deg', 2);
    cases = struct( ...
        'Name', { ...
            'SeaLevel', ...
            'VanNuys', ...
            'Lakeland', ...
            'FortWorth', ...
            'ChennaiHot', ...
            'TorontoColdWindy', ...
            'LakelandAfternoonGusts', ...
            'HighAltitude'}, ...
        'Preset', num2cell(1:8), ...
        'StopTime', num2cell(repmat(6, 1, 8)));
    assert(isequal([cases.Preset], 1:numel(catalog)), ...
        'Parity cases must cover every environment dictionary preset.');
    maxAbsoluteError = zeros(numel(cases), 1);
    maxRelativeError = zeros(numel(cases), 1);
    initialAltitude = zeros(numel(cases), 1);
    minimumAltitude = zeros(numel(cases), 1);
    maximumAirspeed = zeros(numel(cases), 1);
    groundDistance = zeros(numel(cases), 1);
    simulationTime = zeros(numel(cases), 1);
    customOutputs = cell(numel(cases), 1);

    for testIndex = 1:numel(cases)
        testCase = cases(testIndex);
        presetEnvironment = catalog(testCase.Preset);

        selectPreset(mask, blockPath, testCase.Preset);
        presetOutput = runModel( ...
            modelName, testCase.StopTime, presetEnvironment, flight);
        presetMetrics = assertAirborneFlight( ...
            presetOutput, presetEnvironment, flight, ...
            sprintf('%s preset', testCase.Name));

        selectCustom(mask, blockPath, presetEnvironment);

        customEnvironment = EnvironmentMask.resolveForBlock(blockPath);
        assert(isequaln(presetEnvironment, customEnvironment), ...
            'Custom schema differs from preset %d.', testCase.Preset);
        baseInitial = evalin('base', 'initial');
        assert(baseInitial.Latitude == presetEnvironment.Latitude_deg);
        assert(baseInitial.Longitude == presetEnvironment.Longitude_deg);
        assert(baseInitial.Altitude_MSL == ...
            presetEnvironment.Elevation_MSL_m);

        tic;
        customOutput = runModel( ...
            modelName, testCase.StopTime, customEnvironment, flight);
        simulationTime(testIndex) = toc;
        assertAirborneFlight( ...
            customOutput, customEnvironment, flight, ...
            sprintf('%s custom', testCase.Name));
        customOutputs{testIndex} = customOutput;
        [maxAbsoluteError(testIndex), maxRelativeError(testIndex)] = ...
            comparePerformance(presetOutput, customOutput);
        initialAltitude(testIndex) = presetMetrics.InitialAltitudeAGL_m;
        minimumAltitude(testIndex) = presetMetrics.MinimumAltitudeAGL_m;
        maximumAirspeed(testIndex) = presetMetrics.MaximumAirspeed_mps;
        groundDistance(testIndex) = presetMetrics.MaximumGroundDistance_m;

        assert(maxAbsoluteError(testIndex) <= 1e-9, ...
            ['Preset %d and its custom equivalent produced different ' ...
             'performance traces (max absolute error %.3g).'], ...
             testCase.Preset, maxAbsoluteError(testIndex));
    end

    sensitivityResults = runSensitivityTests( ...
        mask, blockPath, modelName, catalog(1), customOutputs{1}, flight);

    results = table( ...
        string({cases.Name})', ...
        [cases.Preset]', ...
        [cases.StopTime]', ...
        initialAltitude, ...
        minimumAltitude, ...
        maximumAirspeed, ...
        groundDistance, ...
        maxAbsoluteError, ...
        maxRelativeError, ...
        simulationTime, ...
        'VariableNames', { ...
            'Case', 'Preset', 'StopTime_s', 'InitialAGL_m', ...
            'MinimumAGL_m', 'MaxTAS_mps', 'MaxGroundDistance_m', ...
            'MaxAbsError', 'MaxRelError', 'CustomRunTime_s'});
    disp(results);
    disp(sensitivityResults);

    clear cleanup
end

function selectPreset(mask, blockPath, presetNumber)
    mask.getParameter('envPreset').Value = ...
        EnvironmentMask.optionForPreset(presetNumber);
    EnvironmentMask.selectionChanged(blockPath);
    set_param(bdroot(blockPath), 'SimulationCommand', 'update');
    assertSourceChoice(blockPath, false);
end

function selectCustom(mask, blockPath, environment)
    populateCustomMask(mask, environment);
    mask.getParameter('envPreset').Value = EnvironmentMask.customOption;
    EnvironmentMask.selectionChanged(blockPath);
    set_param(bdroot(blockPath), 'SimulationCommand', 'update');
    assertSourceChoice(blockPath, true);
end

function assertSourceChoice(blockPath, expectCustom)
    sourceBlock = [blockPath '/Environment Source'];
    customChoice = [sourceBlock '/Custom Environment Parameters'];
    presetChoice = [sourceBlock '/Preset Environment Parameters'];

    expectedCustomState = onOff(expectCustom);
    expectedPresetState = onOff(~expectCustom);
    assert(strcmp(get_param(customChoice, 'CompiledIsActive'), ...
        expectedCustomState), ...
        'Unexpected activation state for the custom environment choice.');
    assert(strcmp(get_param(presetChoice, 'CompiledIsActive'), ...
        expectedPresetState), ...
        'Unexpected activation state for the preset environment choice.');

    customTabs = Simulink.Mask.get(blockPath).getDialogControl( ...
        'customEnvironmentTabs');
    assert(strcmp(customTabs.Visible, expectedCustomState), ...
        'Custom mask fields have the wrong visibility state.');
end

function value = onOff(condition)
    if condition
        value = 'on';
    else
        value = 'off';
    end
end

function populateCustomMask(mask, environment)
    setValue(mask, 'customName', environment.Name);
    setValue(mask, 'customDescription', environment.Description);
    setValue(mask, 'customMultiplier', environment.Multiplier);
    setValue(mask, 'customCompetitionSite', environment.CompetitionSite);

    setValue(mask, 'customLocationName', environment.Location.Name);
    setValue(mask, 'customCity', environment.Location.City);
    setValue(mask, 'customCountry', environment.Location.Country);
    setValue(mask, 'customLatitude_deg', environment.Location.Latitude_deg);
    setValue(mask, 'customLongitude_deg', environment.Location.Longitude_deg);
    setValue(mask, 'customElevation_MSL_m', ...
        environment.Location.Elevation_MSL_m);

    setValue(mask, 'customAtmosphereElevation_MSL_m', ...
        environment.Atmosphere.Elevation_MSL_m);
    setValue(mask, 'customISADeviation_C', ...
        environment.Atmosphere.ISA_Deviation_C);
    setValue(mask, 'customTemperature_C', ...
        environment.Atmosphere.Temperature_C);
    setValue(mask, 'customPressure_Pa', ...
        environment.Atmosphere.Pressure_Pa);
    setValue(mask, 'customDensity_kgm3', ...
        environment.Atmosphere.Density_kgm3);

    setValue(mask, 'customWindShearSpeed_mps', ...
        environment.WindShear.Speed_6m_mps);
    setValue(mask, 'customWindShearDirection_deg', ...
        environment.WindShear.Direction_deg);
    setValue(mask, 'customWindShearExponent', ...
        environment.WindShear.Exponent);

    setValue(mask, 'customTurbulenceOn', ...
        environment.Turbulence.TurbulenceOn);
    setValue(mask, 'customTurbulenceSpeed_mps', ...
        environment.Turbulence.Speed_6m_mps);
    setValue(mask, 'customTurbulenceDirection_deg', ...
        environment.Turbulence.Direction_deg);
    setValue(mask, 'customTurbulenceSigma_mps', ...
        environment.Turbulence.Sigma_mps);
    setValue(mask, 'customTurbulenceScale_m', ...
        environment.Turbulence.Scale_Lu_m);
    setValue(mask, 'customNoiseSeeds', ...
        environment.Turbulence.NoiseSeeds);

    setValue(mask, 'customGustEnableU', environment.Gust.EnableU);
    setValue(mask, 'customGustEnableV', environment.Gust.EnableV);
    setValue(mask, 'customGustEnableW', environment.Gust.EnableW);
    setValue(mask, 'customGustAmplitude_mps', ...
        environment.Gust.Amplitude_mps);
    setValue(mask, 'customGustLength_m', environment.Gust.Length_m);
    setValue(mask, 'customGustStartTime_s', environment.Gust.StartTime_s);
    setValue(mask, 'customGustStartAltitude_AGL_m', ...
        environment.Gust.StartAltitude_AGL_m);
end

function setValue(mask, name, value)
    if islogical(value)
        if value
            text = 'on';
        else
            text = 'off';
        end
    elseif isnumeric(value)
        text = mat2str(value, 17);
    else
        text = char(value);
    end
    mask.getParameter(name).Value = text;
end

function output = runModel(modelName, stopTime, environment, flight)
    equationOfMotion = ...
        [modelName '/Aircraft Dynamics/Equation of motion'];
    joystickBlocks = find_system(modelName, ...
        'LookUnderMasks', 'all', ...
        'FollowLinks', 'on', ...
        'MatchFilter', @Simulink.match.allVariants, ...
        'MaskType', 'Simulation 3D Joystick');
    assert(isscalar(joystickBlocks), ...
        'Expected one Simulation 3D Joystick source.');
    altitudeMSL = environment.Location.Elevation_MSL_m + ...
        flight.AltitudeAGL_m;

    input = Simulink.SimulationInput(modelName);
    input = input.setModelParameter( ...
        'StopTime', num2str(stopTime), ...
        'CaptureErrors', 'on');
    input = input.setBlockParameter( ...
        joystickBlocks{1}, 'Commented', 'on');
    input = input.setBlockParameter( ...
        equationOfMotion, 'xme_0', ...
        mat2str([0 0 -altitudeMSL], 17));
    input = input.setBlockParameter( ...
        equationOfMotion, 'Vm_0', ...
        mat2str([flight.ForwardSpeed_mps 0 0], 17));
    input = input.setBlockParameter( ...
        equationOfMotion, 'eul_0', ...
        mat2str([0 deg2rad(flight.Pitch_deg) deg2rad(-135)], 17));
    input = input.setBlockParameter( ...
        equationOfMotion, 'pm_0', '[0 0 0]');
    output = sim(input);
    if strlength(string(output.ErrorMessage)) > 0
        error('EnvironmentParity:SimulationFailed', ...
            '%s', output.ErrorMessage);
    end
end

function [maxAbsoluteError, maxRelativeError] = ...
        comparePerformance(referenceOutput, customOutput, startTime, endTime)
    if nargin < 3
        startTime = -Inf;
    end
    if nargin < 4
        endTime = Inf;
    end

    signals = { ...
        'ACStates', 'Xe'; ...
        'ACStates', 'Ve'; ...
        'ACStates', 'Euler_angles'; ...
        'FlightParameters', 'TAS'; ...
        'FlightParameters', 'alpha'; ...
        'FlightParameters', 'beta'};

    maxAbsoluteError = 0;
    maxRelativeError = 0;
    for signalIndex = 1:size(signals, 1)
        referenceGroup = referenceOutput.(signals{signalIndex, 1});
        customGroup = customOutput.(signals{signalIndex, 1});
        reference = referenceGroup.(signals{signalIndex, 2});
        custom = customGroup.(signals{signalIndex, 2});

        assert(isequal(reference.Time, custom.Time), ...
            'Time vectors differ for %s.%s.', ...
            signals{signalIndex, 1}, signals{signalIndex, 2});
        assert(isequal(size(reference.Data), size(custom.Data)), ...
            'Signal dimensions differ for %s.%s.', ...
            signals{signalIndex, 1}, signals{signalIndex, 2});

        selectedRows = reference.Time >= startTime & ...
            reference.Time <= endTime;
        assert(any(selectedRows), ...
            'No samples exist in the requested comparison window.');
        referenceData = selectRows(double(reference.Data), selectedRows);
        customData = selectRows(double(custom.Data), selectedRows);
        assert(isequal(isnan(referenceData), isnan(customData)), ...
            'NaN locations differ for %s.%s.', ...
            signals{signalIndex, 1}, signals{signalIndex, 2});
        assert(isequal(isinf(referenceData), isinf(customData)), ...
            'Inf locations differ for %s.%s.', ...
            signals{signalIndex, 1}, signals{signalIndex, 2});

        finiteValues = isfinite(referenceData) & isfinite(customData);
        if any(finiteValues, 'all')
            difference = abs( ...
                referenceData(finiteValues) - customData(finiteValues));
            signalAbsoluteError = max(difference, [], 'all');
            referenceScale = max(1, ...
                max(abs(referenceData(finiteValues)), [], 'all'));
            signalRelativeError = signalAbsoluteError / referenceScale;
            maxAbsoluteError = max(maxAbsoluteError, signalAbsoluteError);
            maxRelativeError = max(maxRelativeError, signalRelativeError);
        end
    end
end

function selected = selectRows(data, rows)
    indices = repmat({':'}, 1, ndims(data));
    indices{1} = rows;
    selected = data(indices{:});
end

function metrics = assertAirborneFlight( ...
        output, environment, flight, label)
    signals = { ...
        output.ACStates.Xe.Data, ...
        output.ACStates.Ve.Data, ...
        output.ACStates.Euler_angles.Data, ...
        output.FlightParameters.TAS.Data, ...
        output.FlightParameters.alpha.Data, ...
        output.FlightParameters.beta.Data};
    for signalIndex = 1:numel(signals)
        assert(all(isfinite(double(signals{signalIndex})), 'all'), ...
            '%s produced a nonfinite flight-state value.', label);
    end

    position = double(output.ACStates.Xe.Data);
    airspeed = double(output.FlightParameters.TAS.Data);
    altitudeAGL = position(:, 3) - ...
        environment.Location.Elevation_MSL_m;
    horizontalDisplacement = position(:, 1:2) - position(1, 1:2);
    horizontalDistance = vecnorm(horizontalDisplacement, 2, 2);

    metrics.InitialAltitudeAGL_m = altitudeAGL(1);
    metrics.MinimumAltitudeAGL_m = min(altitudeAGL);
    metrics.MaximumAirspeed_mps = max(airspeed, [], 'all');
    metrics.MaximumGroundDistance_m = max(horizontalDistance);

    assert(abs(metrics.InitialAltitudeAGL_m - flight.AltitudeAGL_m) <= 1e-9, ...
        '%s did not start at the requested airborne altitude.', label);
    assert(metrics.MinimumAltitudeAGL_m > 0, ...
        '%s contacted the ground before the test completed.', label);
    assert(metrics.MaximumAirspeed_mps > 10, ...
        '%s did not maintain a meaningful airborne airspeed.', label);
    assert(metrics.MaximumGroundDistance_m > 25, ...
        '%s did not travel far enough to exercise flight dynamics.', label);
end

function results = runSensitivityTests( ...
        mask, blockPath, modelName, baselineEnvironment, ...
        baselineOutput, flight)
    stopTime = 6;

    atmosphereEnvironment = baselineEnvironment;
    atmosphereEnvironment.Name = 'Airborne hot atmosphere';
    atmosphereEnvironment.Description = ...
        'Sensitivity test with an ISA +30 deg C atmosphere';
    atmosphereEnvironment.Atmosphere.ISA_Deviation_C = 30;
    atmosphereEnvironment.Atmosphere.Temperature_C = 45;
    atmosphereEnvironment.Atmosphere.Pressure_Pa = 101325;
    atmosphereEnvironment.Atmosphere.Density_kgm3 = ...
        atmosphereEnvironment.Atmosphere.Pressure_Pa / ...
        (287.05287 * ...
        (atmosphereEnvironment.Atmosphere.Temperature_C + 273.15));
    atmosphereEnvironment.Atmosphere.DensityRatio = ...
        atmosphereEnvironment.Atmosphere.Density_kgm3 / 1.2250;
    selectCustom(mask, blockPath, atmosphereEnvironment);
    assert(isequaln( ...
        EnvironmentMask.resolveForBlock(blockPath), ...
        atmosphereEnvironment));
    atmosphereOutput = runModel( ...
        modelName, stopTime, atmosphereEnvironment, flight);
    assertAirborneFlight( ...
        atmosphereOutput, atmosphereEnvironment, flight, ...
        'Temperature-adjusted density custom case');
    [atmosphereAbsolute, atmosphereRelative] = ...
        compareResponseDifference(baselineOutput, atmosphereOutput);

    windEnvironment = baselineEnvironment;
    windEnvironment.Name = 'Airborne steady wind';
    windEnvironment.Description = 'Sensitivity test with steady west wind';
    windEnvironment.WindShear.Speed_6m_mps = 8;
    windEnvironment.WindShear.Direction_deg = 270;
    windEnvironment.WindShear.Exponent = 0.143;
    selectCustom(mask, blockPath, windEnvironment);
    assert(isequaln( ...
        EnvironmentMask.resolveForBlock(blockPath), windEnvironment));
    windOutput = runModel(modelName, stopTime, windEnvironment, flight);
    assertAirborneFlight( ...
        windOutput, windEnvironment, flight, 'Steady-wind custom case');
    [windAbsolute, windRelative] = ...
        compareResponseDifference(baselineOutput, windOutput);

    turbulenceEnvironment = windEnvironment;
    turbulenceEnvironment.Name = 'Airborne Dryden turbulence';
    turbulenceEnvironment.Description = ...
        'Sensitivity test with moderate Dryden turbulence';
    turbulenceEnvironment.Turbulence.Speed_6m_mps = 8;
    turbulenceEnvironment.Turbulence.Direction_deg = 270;
    turbulenceEnvironment.Turbulence.Sigma_mps = 2.12;
    turbulenceEnvironment.Turbulence.Scale_Lu_m = 205;
    turbulenceEnvironment.Turbulence.TurbulenceOn = true;
    selectCustom(mask, blockPath, turbulenceEnvironment);
    assert(isequaln( ...
        EnvironmentMask.resolveForBlock(blockPath), ...
        turbulenceEnvironment));
    turbulenceOutput = runModel( ...
        modelName, stopTime, turbulenceEnvironment, flight);
    assertAirborneFlight( ...
        turbulenceOutput, turbulenceEnvironment, flight, ...
        'Turbulence custom case');
    [turbulenceAbsolute, turbulenceRelative] = ...
        compareResponseDifference(windOutput, turbulenceOutput);

    gustEnvironment = windEnvironment;
    gustEnvironment.Name = 'Airborne lateral gust';
    gustEnvironment.Description = ...
        'Sensitivity test with a lateral one-cosine gust';
    gustEnvironment.Gust.Amplitude_mps = [0 4 0];
    gustEnvironment.Gust.Length_m = [1 60 1];
    gustEnvironment.Gust.StartTime_s = 1;
    gustEnvironment.Gust.StartAltitude_AGL_m = flight.AltitudeAGL_m;
    gustEnvironment.Gust.EnableU = false;
    gustEnvironment.Gust.EnableV = true;
    gustEnvironment.Gust.EnableW = false;
    selectCustom(mask, blockPath, gustEnvironment);
    assert(isequaln( ...
        EnvironmentMask.resolveForBlock(blockPath), gustEnvironment));
    gustOutput = runModel(modelName, stopTime, gustEnvironment, flight);
    assertAirborneFlight( ...
        gustOutput, gustEnvironment, flight, 'Gust custom case');
    [gustPreAbsolute, ~] = compareResponseDifference( ...
        windOutput, gustOutput, -Inf, 0.99);
    [gustAbsolute, gustRelative] = compareResponseDifference( ...
        windOutput, gustOutput, 1.01, Inf);

    threshold = 1e-6;
    effectObserved = [ ...
        atmosphereAbsolute > threshold; ...
        windAbsolute > threshold; ...
        turbulenceAbsolute > threshold; ...
        gustAbsolute > threshold && gustPreAbsolute <= 1e-9];
    results = table( ...
        ["TemperatureAdjustedDensity"; "SteadyWind"; ...
        "DrydenTurbulence"; "DiscreteGust"], ...
        [atmosphereAbsolute; windAbsolute; ...
        turbulenceAbsolute; gustAbsolute], ...
        [atmosphereRelative; windRelative; ...
        turbulenceRelative; gustRelative], ...
        [NaN; NaN; NaN; gustPreAbsolute], ...
        effectObserved, ...
        'VariableNames', { ...
            'Feature', 'MaxAbsResponseDifference', ...
            'MaxRelResponseDifference', 'PreOnsetMaxAbsDifference', ...
            'EffectObserved'});

    assert(all(effectObserved), ...
        'One or more airborne environment effects were not observed.');
end

function [maxAbsoluteDifference, maxRelativeDifference] = ...
        compareResponseDifference( ...
        referenceOutput, candidateOutput, startTime, endTime)
    if nargin < 3
        startTime = -Inf;
    end
    if nargin < 4
        endTime = Inf;
    end

    signals = { ...
        'ACStates', 'Xe'; ...
        'ACStates', 'Ve'; ...
        'ACStates', 'Euler_angles'; ...
        'FlightParameters', 'TAS'; ...
        'FlightParameters', 'alpha'; ...
        'FlightParameters', 'beta'};
    maxAbsoluteDifference = 0;
    maxRelativeDifference = 0;

    for signalIndex = 1:size(signals, 1)
        referenceGroup = referenceOutput.(signals{signalIndex, 1});
        candidateGroup = candidateOutput.(signals{signalIndex, 1});
        reference = referenceGroup.(signals{signalIndex, 2});
        candidate = candidateGroup.(signals{signalIndex, 2});

        firstTime = max([reference.Time(1), candidate.Time(1), startTime]);
        lastTime = min([reference.Time(end), candidate.Time(end), endTime]);
        assert(firstTime <= lastTime, ...
            'Compared response traces have no overlapping time range.');

        queryTime = unique([ ...
            firstTime; ...
            reference.Time(reference.Time >= firstTime & ...
                reference.Time <= lastTime); ...
            candidate.Time(candidate.Time >= firstTime & ...
                candidate.Time <= lastTime); ...
            lastTime]);
        referenceData = interpolateData(reference, queryTime);
        candidateData = interpolateData(candidate, queryTime);

        finiteValues = isfinite(referenceData) & isfinite(candidateData);
        assert(all(finiteValues, 'all'), ...
            'Sensitivity comparison encountered a nonfinite value.');
        difference = abs(referenceData - candidateData);
        signalAbsoluteDifference = max(difference, [], 'all');
        referenceScale = max(1, max(abs(referenceData), [], 'all'));
        signalRelativeDifference = ...
            signalAbsoluteDifference / referenceScale;
        maxAbsoluteDifference = max( ...
            maxAbsoluteDifference, signalAbsoluteDifference);
        maxRelativeDifference = max( ...
            maxRelativeDifference, signalRelativeDifference);
    end
end

function data = interpolateData(signal, queryTime)
    time = double(signal.Time(:));
    values = double(signal.Data);
    values = reshape(values, numel(time), []);
    [time, uniqueIndices] = unique(time, 'stable');
    values = values(uniqueIndices, :);
    data = interp1(time, values, queryTime, 'linear');
end

function restoreModel(modelName, blockPath, names, values, ...
        originalModelInitial, originalBaseInitial, ...
        originalDirty, wasLoaded)
    try
        mask = Simulink.Mask.get(blockPath);
        for parameterIndex = 1:numel(names)
            mask.getParameter(names{parameterIndex}).Value = ...
                values{parameterIndex};
        end
        EnvironmentMask.selectionChanged(blockPath);
        set_param(modelName, 'SimulationCommand', 'update');
        modelWorkspace = get_param(modelName, 'ModelWorkspace');
        modelWorkspace.assignin('initial', originalModelInitial);
        assignin('base', 'initial', originalBaseInitial);
        set_param(modelName, 'Dirty', originalDirty);
        if ~wasLoaded
            close_system(modelName, 0);
        end
    catch exception
        warning('EnvironmentParity:RestoreFailed', ...
            'Could not restore the original model state: %s', ...
            exception.message);
    end
end
