function configureEnvironmentMask(modelName)
%CONFIGUREENVIRONMENTMASK Add preset and custom environment controls.

    if nargin < 1
        modelName = 'SimulationDemo';
    end

    open_system(modelName);
    environmentBlocks = find_system(modelName, 'SearchDepth', 1, ...
        'MatchFilter', @Simulink.match.allVariants, ...
        'BlockType', 'SubSystem', 'Name', 'Environment');
    if numel(environmentBlocks) ~= 1
        error('configureEnvironmentMask:EnvironmentBlock', ...
            'Expected one top-level Environment subsystem in %s.', modelName);
    end

    blockPath = environmentBlocks{1};
    mask = Simulink.Mask.get(blockPath);
    if isempty(mask)
        error('configureEnvironmentMask:MissingMask', ...
            'The Environment subsystem must already have a mask.');
    end

    mask.Type = 'SAE Aero Environment';
    mask.Description = ['Select a predefined environment or enter a ' ...
        'complete custom environment definition.'];
    mask.Initialization = 'EnvironmentMask.initialize(gcb);';
    mask.SelfModifiable = 'on';
    mask.RunInitForIconRedraw = 'on';
    mask.Display = [ ...
        'try' newline ...
        '    disp(EnvironmentMask.formatIconLabel(environmentName));' newline ...
        'catch' newline ...
        '    disp(''Environment'');' newline ...
        'end'];

    preset = getMaskParameter(mask, 'envPreset');
    if isempty(preset)
        error('configureEnvironmentMask:MissingPreset', ...
            'The Environment mask must contain an envPreset parameter.');
    end
    optionIndex = existingOptionIndex(preset.Value);
    options = EnvironmentMask.presetOptions;
    preset.TypeOptions = options;
    preset.Evaluate = 'off';
    preset.Prompt = 'Environment';
    preset.Callback = 'EnvironmentMask.selectionChanged(gcb);';
    preset.ShowTooltip = 'on';
    preset.DialogControl.Tooltip = ...
        'Choose a catalog environment or enter a custom definition.';

    selectionGroup = getDialogControl(mask, 'Container1');
    if ~isempty(selectionGroup)
        selectionGroup.Prompt = 'Environment source';
        selectionGroup.AlignPrompts = 'on';
    end
    description = getDialogControl(mask, 'Control1');
    if ~isempty(description)
        description.Prompt = ...
            'Predefined environments are loaded from environmentData.sldd.';
    end

    ensureDialogControl(mask, 'tabcontainer', ...
        'customEnvironmentTabs', '', '');
    ensureDialogControl(mask, 'tab', ...
        'customGeneralTab', 'General', 'customEnvironmentTabs');
    ensureDialogControl(mask, 'tab', ...
        'customLocationTab', 'Location', 'customEnvironmentTabs');
    ensureDialogControl(mask, 'tab', ...
        'customAtmosphereTab', 'Atmosphere', 'customEnvironmentTabs');
    ensureDialogControl(mask, 'tab', ...
        'customWindTab', 'Wind shear', 'customEnvironmentTabs');
    ensureDialogControl(mask, 'tab', ...
        'customTurbulenceTab', 'Turbulence', 'customEnvironmentTabs');
    ensureDialogControl(mask, 'tab', ...
        'customGustTab', 'Gust', 'customEnvironmentTabs');

    ensureParameter(mask, 'edit', 'customName', ...
        'Name', 'Custom Environment', 'off', 'customGeneralTab', ...
        'Name stored with simulation environment metadata.');
    ensureParameter(mask, 'edit', 'customDescription', ...
        'Description', 'User-defined environment', 'off', ...
        'customGeneralTab', 'Description stored with the environment.');
    ensureParameter(mask, 'edit', 'customMultiplier', ...
        'Score multiplier', '1', 'on', 'customGeneralTab', ...
        'Positive mission score multiplier.');
    ensureParameter(mask, 'checkbox', 'customCompetitionSite', ...
        'Competition site', 'off', 'on', 'customGeneralTab', ...
        'Marks this environment as an official competition site.');

    ensureParameter(mask, 'edit', 'customLocationName', ...
        'Location name', 'Custom Site', 'off', 'customLocationTab', ...
        'Airfield or test-site name.');
    ensureParameter(mask, 'edit', 'customCity', ...
        'City', '', 'off', 'customLocationTab', 'Location city.');
    ensureParameter(mask, 'edit', 'customCountry', ...
        'Country or region', '', 'off', 'customLocationTab', ...
        'Location country or region.');
    ensureParameter(mask, 'edit', 'customLatitude_deg', ...
        'Latitude [deg]', '0', 'on', 'customLocationTab', ...
        'Geodetic latitude from -90 to 90 degrees.');
    ensureParameter(mask, 'edit', 'customLongitude_deg', ...
        'Longitude [deg]', '0', 'on', 'customLocationTab', ...
        'Longitude from -180 to 180 degrees.');
    ensureParameter(mask, 'edit', 'customElevation_MSL_m', ...
        'Elevation MSL [m]', '0', 'on', 'customLocationTab', ...
        'Site elevation above mean sea level.');

    ensureParameter(mask, 'edit', 'customAtmosphereElevation_MSL_m', ...
        'Reference elevation [m]', '0', 'on', 'customAtmosphereTab', ...
        'Elevation associated with the atmospheric measurements.');
    ensureParameter(mask, 'edit', 'customISADeviation_C', ...
        'ISA deviation [deg C]', '0', 'on', 'customAtmosphereTab', ...
        'Temperature difference from ISA.');
    ensureParameter(mask, 'edit', 'customTemperature_C', ...
        'Temperature [deg C]', '15', 'on', 'customAtmosphereTab', ...
        'Measured or specified air temperature.');
    ensureParameter(mask, 'edit', 'customPressure_Pa', ...
        'Pressure [Pa]', '101325', 'on', 'customAtmosphereTab', ...
        'Positive static air pressure.');
    ensureParameter(mask, 'edit', 'customDensity_kgm3', ...
        'Density [kg/m^3]', '1.225', 'on', 'customAtmosphereTab', ...
        'Positive air density.');

    ensureParameter(mask, 'edit', 'customWindShearSpeed_mps', ...
        'Speed at 6 m [m/s]', '0', 'on', 'customWindTab', ...
        'Nonnegative wind speed at the reference height.');
    ensureParameter(mask, 'edit', 'customWindShearDirection_deg', ...
        'Direction [deg]', '0', 'on', 'customWindTab', ...
        'Meteorological direction clockwise from north.');
    ensureParameter(mask, 'edit', 'customWindShearExponent', ...
        'Power-law exponent', '0.143', 'on', 'customWindTab', ...
        'Positive terrain-dependent shear exponent.');

    ensureParameter(mask, 'checkbox', 'customTurbulenceOn', ...
        'Enable turbulence', 'off', 'on', 'customTurbulenceTab', ...
        'Enable the Dryden turbulence model.');
    ensureParameter(mask, 'edit', 'customTurbulenceSpeed_mps', ...
        'Speed at 6 m [m/s]', '0', 'on', 'customTurbulenceTab', ...
        'Nonnegative mean wind speed used by Dryden turbulence.');
    ensureParameter(mask, 'edit', 'customTurbulenceDirection_deg', ...
        'Direction [deg]', '0', 'on', 'customTurbulenceTab', ...
        'Direction clockwise from north.');
    ensureParameter(mask, 'edit', 'customTurbulenceSigma_mps', ...
        'Sigma [m/s]', '0', 'on', 'customTurbulenceTab', ...
        'RMS turbulence intensity.');
    ensureParameter(mask, 'edit', 'customTurbulenceScale_m', ...
        'Scale length [m]', '205', 'on', 'customTurbulenceTab', ...
        'Positive medium/high-altitude scale length.');
    ensureParameter(mask, 'edit', 'customNoiseSeeds', ...
        'Noise seeds [1x4]', '[23341 23342 23343 23344]', 'on', ...
        'customTurbulenceTab', 'Four nonnegative integer seeds.');

    ensureParameter(mask, 'checkbox', 'customGustEnableU', ...
        'Enable U-axis gust', 'off', 'on', 'customGustTab', ...
        'Enable longitudinal gust.');
    ensureParameter(mask, 'checkbox', 'customGustEnableV', ...
        'Enable V-axis gust', 'off', 'on', 'customGustTab', ...
        'Enable lateral gust.');
    ensureParameter(mask, 'checkbox', 'customGustEnableW', ...
        'Enable W-axis gust', 'off', 'on', 'customGustTab', ...
        'Enable vertical gust.');
    ensureParameter(mask, 'edit', 'customGustAmplitude_mps', ...
        'Amplitude [u v w] m/s', '[0 0 0]', 'on', 'customGustTab', ...
        'Three gust velocity components.');
    ensureParameter(mask, 'edit', 'customGustLength_m', ...
        'Length [dx dy dz] m', '[1 1 1]', 'on', 'customGustTab', ...
        'Three positive gust wavelengths.');
    ensureParameter(mask, 'edit', 'customGustStartTime_s', ...
        'Start time [s]', 'Inf', 'on', 'customGustTab', ...
        'Nonnegative gust start time; use Inf to disable by time.');
    ensureParameter(mask, 'edit', 'customGustStartAltitude_AGL_m', ...
        'Start altitude AGL [m]', '0', 'on', 'customGustTab', ...
        'Nonnegative gust onset altitude.');

    preset.Value = options{optionIndex};
    EnvironmentMask.selectionChanged(blockPath);
    save_system(modelName);
end

function ensureDialogControl(mask, type, name, prompt, container)
    control = getDialogControl(mask, name);
    if isempty(control)
        arguments = {'Type', type, 'Name', name};
        if ~isempty(prompt)
            arguments = [arguments, {'Prompt', prompt}];
        end
        if ~isempty(container)
            arguments = [arguments, {'Container', container}];
        end
        mask.addDialogControl(arguments{:});
    else
        if ~isempty(prompt) && isprop(control, 'Prompt')
            control.Prompt = prompt;
        end
    end
end

function ensureParameter(mask, type, name, prompt, defaultValue, ...
        evaluate, container, tooltip)
    parameter = getMaskParameter(mask, name);
    if isempty(parameter)
        parameter = mask.addParameter( ...
            'Type', type, ...
            'Name', name, ...
            'Prompt', prompt, ...
            'Value', defaultValue, ...
            'Evaluate', evaluate, ...
            'Tunable', 'off', ...
            'ShowTooltip', 'on', ...
            'Container', container);
    else
        parameter.Prompt = prompt;
        parameter.Evaluate = evaluate;
        parameter.Tunable = 'off';
        parameter.ShowTooltip = 'on';
    end
    parameter.DialogControl.Tooltip = tooltip;
end

function parameter = getMaskParameter(mask, name)
    try
        parameter = mask.getParameter(name);
    catch
        parameter = [];
    end
end

function control = getDialogControl(mask, name)
    try
        control = mask.getDialogControl(name);
    catch
        control = [];
    end
end

function index = existingOptionIndex(value)
    options = EnvironmentMask.presetOptions;
    text = strtrim(char(string(value)));
    numericSelection = str2double(text);
    if isfinite(numericSelection) && ismember(numericSelection, [0 9])
        index = 1;
        return;
    elseif isfinite(numericSelection) && ismember(numericSelection, 1:8)
        index = numericSelection + 1;
        return;
    end

    index = find(strcmp(text, options), 1);
    if isempty(index)
        if contains(text, 'Custom', 'IgnoreCase', true)
            index = 1;
        elseif contains(text, 'Sea Level', 'IgnoreCase', true)
            index = 2;
        elseif contains(text, 'Van Nuys', 'IgnoreCase', true)
            index = 3;
        elseif contains(text, 'Fort Worth', 'IgnoreCase', true)
            index = 5;
        elseif contains(text, 'Hot Day', 'IgnoreCase', true)
            index = 6;
        elseif contains(text, 'Cold Windy', 'IgnoreCase', true)
            index = 7;
        elseif contains(text, 'Gust', 'IgnoreCase', true)
            index = 8;
        elseif contains(text, 'High', 'IgnoreCase', true) && ...
                contains(text, 'Altitude', 'IgnoreCase', true)
            index = 9;
        elseif contains(text, 'Lakeland', 'IgnoreCase', true)
            index = 4;
        end
    end
    if isempty(index)
        index = 1;
    end
end
